# ----------------
# STEP 1:
# Build Openzwave and Zwave2Mqtt pkg
# All result files will be put in /dist folder
FROM __BUILD_ARCH__/node:carbon-alpine AS build

__CROSS_COPY bin/qemu-__QEMU__-static /usr/bin/

# Set the commit of Zwave2Mqtt to checkout when cloning the repo
ENV Z2M_VERSION=a569258a4a28d7818657653e395b15bd11e0bc91

# Install required dependencies
RUN apk update && apk --no-cache add \
      gnutls \
      gnutls-dev \
      libusb \
      eudev \
      # Install build dependencies
    && apk --no-cache --virtual .build-deps add \
      coreutils \
      eudev-dev \
      build-base \
      git \
      python \
      bash \
      libusb-dev \
      linux-headers \
      wget \
      tar  \
      openssl \
      make 

# Get latest stable 1.6 and move binaries in /dist/lib and devices db on /dist/db
RUN cd /root \
    && wget http://old.openzwave.com/downloads/openzwave-1.6.962.tar.gz \
    && tar zxvf openzwave-*.gz \
    && cd openzwave-* && make && make install \
    && mkdir -p /dist/lib \
    && mv libopenzwave.so* /dist/lib/ \
    && mkdir -p /dist/db \
    && mv config/* /dist/db

COPY bin/package.sh /root/package.sh

# Clone Zwave2Mqtt build pkg files and move them to /dist/pkg
RUN npm config set unsafe-perm true && npm install -g pkg@4.3.8 \
    && cd /root \
    && git clone https://github.com/OpenZWave/Zwave2Mqtt.git  \
    && cd Zwave2Mqtt \
    && git checkout ${Z2M_VERSION} \
    && npm install \
    && npm run build

RUN cd /root \
    && chmod +x package.sh && ./package.sh \
    && mkdir -p /dist/pkg \
    && mv /root/Zwave2Mqtt/pkg/* /dist/pkg    

# Clean up
RUN rm -R /root/* && apk del .build-deps

# ----------------
# STEP 2:
# Run a minimal alpine image
FROM __DOCKER_ARCH__/alpine:latest

COPY bin/qemu-__QEMU__-static /usr/bin/

LABEL maintainer="robertsLando"

RUN apk update && apk add --no-cache \
    libstdc++  \
    libgcc \
    libusb \
    tzdata \
    eudev 

# Copy files from previous build stage
COPY --from=build /dist/lib/ /lib/
COPY --from=build /dist/db/ /usr/local/etc/openzwave/ 
COPY --from=build /dist/pkg /usr/src/app

# Set enviroment
ENV LD_LIBRARY_PATH /lib

WORKDIR /usr/src/app

EXPOSE 8091

# Override default alpine entrypoint
ENTRYPOINT [""]

CMD ["/usr/src/app/zwave2mqtt"]